# Makes use of package arduino-makefile https://github.com/sudar/Arduino-Makefile

# user foir deumilanove or diecimila
BOARD_TAG = diecimila
#BOARD_TAG = duo
MONITOR_PORT = /dev/ttyUSB0

include ../TPLs/Arduino-Makefile/Arduino.mk

# things this makefile needs to complete toolchain
#ARDUINO_DIR = /usr/include
#ARDMK_DIR = /usr/bin
#AVR_TOOLS_DIR = /usr/

#USER_LIB_PATH += ../../TPLs/SparkFunMPU9250BreakoutArduinoLibrary/src
#ARDUINO_LIB_PATH += ../../TPLs/SparkFunMPU9250BreakoutArduinoLibrary/src


